/* ==========================================================
   QUIZ_DATA — pytania wygenerowane z docs/interview-prep.md
   Każde pytanie:
     id    — unikalny identyfikator
     cat   — kategoria (musi istnieć w --cat-* w style.css)
     type  — 'single' | 'multi'
     q     — { pl, en } treść pytania
     a     — [{ pl, en, ok }] odpowiedzi (ok: true = poprawna)
     exp   — { pl, en } wyjaśnienie pokazywane po sprawdzeniu
     topic — { pl, en } nazwa tematu do listy powtórki
   ========================================================== */
(function () {
  'use strict';

  const QUIZ_DATA = [
    /* ── ANGULAR ─────────────────────────────────────────── */
    {
      id: 'ng-signals-computed',
      cat: 'angular', type: 'single',
      q: { pl: 'Co robi `computed()` w Angular Signals?',
           en: 'What does `computed()` do in Angular Signals?' },
      a: [
        { pl: 'Tworzy memoizowany signal pochodny, który sam śledzi zależności',
          en: 'Creates a memoized derived signal that tracks dependencies automatically', ok: true },
        { pl: 'Uruchamia side-effect przy każdej zmianie dowolnego signala',
          en: 'Runs a side-effect on every change of any signal', ok: false },
        { pl: 'Konwertuje Observable na signal z auto-unsubscribe',
          en: 'Converts an Observable to a signal with auto-unsubscribe', ok: false },
        { pl: 'Tworzy writable signal z wartością początkową',
          en: 'Creates a writable signal with an initial value', ok: false },
      ],
      exp: { pl: '`computed()` = derywacja wartości (pure, memo). `effect()` to side-effects, `toSignal()` konwertuje Observable, a `signal()` tworzy writable.',
             en: '`computed()` is a pure, memoized derivation. `effect()` is for side-effects, `toSignal()` converts Observables, `signal()` creates writables.' },
      topic: { pl: 'Angular Signals — computed vs effect', en: 'Angular Signals — computed vs effect' },
    },
    {
      id: 'ng-zoneless',
      cat: 'angular', type: 'single',
      q: { pl: 'Co jest głównym mechanizmem wyzwalającym change detection w aplikacji Zoneless?',
           en: 'What triggers change detection in a Zoneless app?' },
      a: [
        { pl: 'Signals oraz async pipe; brak zone.js w bundle',
          en: 'Signals and async pipe; no zone.js in the bundle', ok: true },
        { pl: 'zone.js patchuje setTimeout i fetch jak wcześniej',
          en: 'zone.js keeps patching setTimeout and fetch as before', ok: false },
        { pl: 'Angular ręcznie skanuje DOM po każdym evencie',
          en: 'Angular manually scans the DOM after every event', ok: false },
        { pl: 'MutationObserver wywołuje CD przy zmianie HTML',
          en: 'MutationObserver fires CD on any HTML change', ok: false },
      ],
      exp: { pl: 'W Zoneless zone.js znika. CD wyzwalają sygnały, async pipe i jawne API (`markForCheck`). Plus: mniejszy bundle, czystsze stack traces.',
             en: 'Zoneless drops zone.js. CD is fired by signals, async pipe and explicit APIs (`markForCheck`). Bonus: smaller bundle and cleaner stack traces.' },
      topic: { pl: 'Zoneless Change Detection', en: 'Zoneless change detection' },
    },
    {
      id: 'ng-onpush-triggers',
      cat: 'angular', type: 'multi',
      q: { pl: 'Które sytuacje wyzwalają sprawdzenie komponentu z `ChangeDetectionStrategy.OnPush`?',
           en: 'Which cases trigger a check on an `OnPush` component?' },
      a: [
        { pl: 'Zmiana referencji `@Input`', en: 'A change in `@Input` reference', ok: true },
        { pl: 'Event wyemitowany w szablonie komponentu', en: 'An event emitted from the component template', ok: true },
        { pl: 'Async pipe wypuścił nową wartość', en: 'Async pipe emitted a new value', ok: true },
        { pl: 'Mutacja tablicy przez `push()` bez zmiany referencji', en: 'Mutating an array via `push()` without changing the reference', ok: false },
        { pl: 'Odczytany w template signal został zaktualizowany', en: 'A signal used in the template was updated', ok: true },
      ],
      exp: { pl: 'OnPush sprawdza komponent tylko na: zmianę referencji input, event z template, async pipe emit lub update signala używanego w template. Mutacja tablicy nie zmienia referencji — brak re-renderu.',
             en: 'OnPush only checks on: input reference change, template event, async pipe emission, or a signal update used in the template. Mutating an array keeps the reference — no re-render.' },
      topic: { pl: 'OnPush — kiedy odpali CD', en: 'OnPush — when CD fires' },
    },
    {
      id: 'ng-defer-triggers',
      cat: 'angular', type: 'multi',
      q: { pl: 'Które triggery dla `@defer` są wbudowane w Angular?',
           en: 'Which `@defer` triggers are built-in in Angular?' },
      a: [
        { pl: '`on idle`', en: '`on idle`', ok: true },
        { pl: '`on viewport`', en: '`on viewport`', ok: true },
        { pl: '`on hover`', en: '`on hover`', ok: true },
        { pl: '`on network:fast`', en: '`on network:fast`', ok: false },
        { pl: '`on interaction`', en: '`on interaction`', ok: true },
        { pl: '`when <condition>`', en: '`when <condition>`', ok: true },
      ],
      exp: { pl: 'Wbudowane triggery: `on idle / viewport / hover / interaction / immediate / timer / when`. Nie ma `on network:*`.',
             en: 'Built-ins: `on idle / viewport / hover / interaction / immediate / timer / when`. No `on network:*`.' },
      topic: { pl: 'Deferrable Views — triggery', en: 'Deferrable views — triggers' },
    },
    {
      id: 'ng-for-track',
      cat: 'angular', type: 'single',
      q: { pl: 'Dlaczego `@for` wymaga `track`?',
           en: 'Why is `track` required in `@for`?' },
      a: [
        { pl: 'Bez niego Angular musiałby re-renderować wszystkie elementy przy każdej zmianie tablicy',
          en: 'Without it Angular would re-render every item on each array change', ok: true },
        { pl: 'Jest tylko wymogiem lint-owym, można go pominąć',
          en: 'It is only a lint rule that can be skipped', ok: false },
        { pl: 'Umożliwia filtrowanie listy po kliknięciu',
          en: 'It enables list filtering on click', ok: false },
        { pl: 'Włącza OnPush na dziecku', en: 'It turns on OnPush on the child', ok: false },
      ],
      exp: { pl: '`track` to performance-by-default — zastąpił opcjonalny `trackBy` z `*ngFor`. Bez niego nie ma możliwości stabilnego mapowania elementów między renderami.',
             en: '`track` is performance-by-default — it replaced the optional `trackBy` from `*ngFor`. Without it there is no stable mapping between renders.' },
      topic: { pl: 'Control flow — @for i track', en: 'Control flow — @for and track' },
    },
    {
      id: 'ng-inject',
      cat: 'angular', type: 'single',
      q: { pl: 'Którą przewagę daje `inject()` nad DI przez konstruktor?',
           en: 'What is the advantage of `inject()` over constructor DI?' },
      a: [
        { pl: 'Działa też poza klasami — w funkcyjnych guardach, resolverach, interceptorach',
          en: 'It also works outside classes — in functional guards, resolvers, interceptors', ok: true },
        { pl: 'Jest szybsze w runtime', en: 'It is faster at runtime', ok: false },
        { pl: 'Pozwala wstrzyknąć provider spoza drzewa DI', en: 'It lets you inject providers outside the DI tree', ok: false },
        { pl: 'Automatycznie mockuje serwisy w testach', en: 'It auto-mocks services in tests', ok: false },
      ],
      exp: { pl: 'Główna wygrana: użycie poza klasami (`const auth = inject(AuthService)` w funkcjonalnym interceptorze) oraz czytelniejszy kod komponentów.',
             en: 'The real win is usage outside classes (e.g. `const auth = inject(AuthService)` in a functional interceptor) and cleaner component code.' },
      topic: { pl: 'DI — inject() vs constructor', en: 'DI — inject() vs constructor' },
    },
    {
      id: 'ng-canmatch-vs-canactivate',
      cat: 'angular', type: 'single',
      q: { pl: 'Czym różni się `CanMatchFn` od `CanActivateFn`?',
           en: 'What is the difference between `CanMatchFn` and `CanActivateFn`?' },
      a: [
        { pl: '`CanMatch` decyduje, czy route w ogóle pasuje — może pominąć lazy load; `CanActivate` odpala się już po dopasowaniu',
          en: '`CanMatch` decides if the route matches at all — can skip lazy loading; `CanActivate` runs after a match', ok: true },
        { pl: 'To aliasy, robią dokładnie to samo', en: 'They are aliases doing exactly the same thing', ok: false },
        { pl: '`CanMatch` działa tylko dla SSR', en: '`CanMatch` only works with SSR', ok: false },
        { pl: '`CanActivate` obsługuje tylko Promise, `CanMatch` tylko Observable', en: '`CanActivate` only handles Promises, `CanMatch` only Observables', ok: false },
      ],
      exp: { pl: 'Dla guardów bazujących na roli często lepszy `CanMatch` — nie ładuje niepotrzebnego chunka i pozwala łatwo fallback-ować na inny route.',
             en: 'For role-based guards `CanMatch` is often better — avoids loading the chunk and lets you fallback to another matching route.' },
      topic: { pl: 'Routing — CanMatch vs CanActivate', en: 'Routing — CanMatch vs CanActivate' },
    },
    {
      id: 'ng-standalone-default',
      cat: 'angular', type: 'single',
      q: { pl: 'Jaki jest domyślny tryb komponentu w Angular 21?',
           en: 'What is the default component mode in Angular 21?' },
      a: [
        { pl: 'Standalone — bez NgModule', en: 'Standalone — no NgModule', ok: true },
        { pl: 'NgModule zostaje domyślnie', en: 'NgModule remains the default', ok: false },
        { pl: 'Każdy komponent jest Web Component', en: 'Every component is a Web Component', ok: false },
        { pl: 'Signal Component', en: 'Signal Component', ok: false },
      ],
      exp: { pl: 'Od Angulara 19 `standalone: true` jest domyślny. Moduły dalej działają, ale nowy kod piszemy bez nich.',
             en: 'Since Angular 19 `standalone: true` is the default. Modules still work, but new code is written without them.' },
      topic: { pl: 'Standalone components', en: 'Standalone components' },
    },
    {
      id: 'ng-hydration-mismatch',
      cat: 'angular', type: 'single',
      q: { pl: 'Dlaczego hydration mismatch jest problemem?',
           en: 'Why is a hydration mismatch a problem?' },
      a: [
        { pl: 'Serwer i klient wygenerowały inny DOM — Angular robi warning i może wykonać pełen re-render, psując UX',
          en: 'Server and client produced different DOM — Angular warns and may do a full re-render, hurting UX', ok: true },
        { pl: 'Jest tylko estetyczny, nie wpływa na działanie', en: 'It is only cosmetic, no runtime impact', ok: false },
        { pl: 'Powoduje 500 na serwerze', en: 'It causes a 500 on the server', ok: false },
        { pl: 'Blokuje lazy loading', en: 'It blocks lazy loading', ok: false },
      ],
      exp: { pl: 'Typowe źródła: `Date.now()` / `Math.random()` w template, odczyt `localStorage` bez `isPlatformBrowser`, różne daty/lokalizacje między serwerem a klientem.',
             en: 'Common causes: `Date.now()`/`Math.random()` in templates, reading `localStorage` without `isPlatformBrowser`, different locales/dates between server and client.' },
      topic: { pl: 'SSR — hydration mismatch', en: 'SSR — hydration mismatch' },
    },
    {
      id: 'ng-takeuntildestroyed',
      cat: 'angular', type: 'single',
      q: { pl: 'Do czego służy `takeUntilDestroyed()`?',
           en: 'What is `takeUntilDestroyed()` for?' },
      a: [
        { pl: 'Automatycznie odsubskrybuje observable przy zniszczeniu kontekstu (komponentu / serwisu)',
          en: 'Automatically unsubscribes an observable when the context (component/service) is destroyed', ok: true },
        { pl: 'Anuluje Promise po timeoucie', en: 'Cancels a Promise after a timeout', ok: false },
        { pl: 'Subskrybuje się do destroy lifecycle hook', en: 'Subscribes to the destroy lifecycle hook', ok: false },
        { pl: 'Niszczy komponent z poziomu szablonu', en: 'Destroys a component from the template', ok: false },
      ],
      exp: { pl: 'Od Angulara 16. Używane w context injection lub z jawnym `DestroyRef`. Zastępuje ręczny `destroy$` + `takeUntil`.',
             en: 'Available since Angular 16. Used in injection context or with an explicit `DestroyRef`. Replaces the manual `destroy$` + `takeUntil` pattern.' },
      topic: { pl: 'RxJS — takeUntilDestroyed', en: 'RxJS — takeUntilDestroyed' },
    },

    /* ── RXJS ────────────────────────────────────────────── */
    {
      id: 'rx-switchmap-autocomplete',
      cat: 'rxjs', type: 'single',
      q: { pl: 'Który operator jest najlepszy do autocomplete (anulowanie poprzedniego requestu)?',
           en: 'Which operator is best for autocomplete (cancel previous request)?' },
      a: [
        { pl: '`switchMap`', en: '`switchMap`', ok: true },
        { pl: '`mergeMap`', en: '`mergeMap`', ok: false },
        { pl: '`concatMap`', en: '`concatMap`', ok: false },
        { pl: '`exhaustMap`', en: '`exhaustMap`', ok: false },
      ],
      exp: { pl: '`switchMap` anuluje poprzednią subskrypcję — ostatni "wygrywa". To domyślny wybór dla autocomplete, nawigacji, live search.',
             en: '`switchMap` cancels the previous inner — last one wins. The default choice for autocomplete, navigation, live search.' },
      topic: { pl: 'switchMap vs mergeMap vs concatMap vs exhaustMap', en: 'switchMap vs mergeMap vs concatMap vs exhaustMap' },
    },
    {
      id: 'rx-exhaustmap-submit',
      cat: 'rxjs', type: 'single',
      q: { pl: 'Który operator wybierzesz, by ignorować kliknięcia "Submit" dopóki trwa poprzedni request?',
           en: 'Which operator do you pick to ignore "Submit" clicks while the previous request is in flight?' },
      a: [
        { pl: '`exhaustMap`', en: '`exhaustMap`', ok: true },
        { pl: '`switchMap`', en: '`switchMap`', ok: false },
        { pl: '`mergeMap`', en: '`mergeMap`', ok: false },
        { pl: '`concatMap`', en: '`concatMap`', ok: false },
      ],
      exp: { pl: '`exhaustMap` ignoruje nowe wartości, gdy inner observable jest aktywny — idealne dla login/submit, żeby nie strzelać dubletami.',
             en: '`exhaustMap` ignores new values while the inner is active — perfect for login/submit to prevent duplicate requests.' },
      topic: { pl: 'exhaustMap — przypadki użycia', en: 'exhaustMap — use cases' },
    },
    {
      id: 'rx-subjects',
      cat: 'rxjs', type: 'single',
      q: { pl: 'Czym różni się `BehaviorSubject` od `Subject`?',
           en: 'How does `BehaviorSubject` differ from `Subject`?' },
      a: [
        { pl: '`BehaviorSubject` ma wartość początkową i od razu emituje ostatnią wartość nowemu subskrybentowi',
          en: '`BehaviorSubject` holds an initial value and emits the latest value to any new subscriber', ok: true },
        { pl: '`BehaviorSubject` jest tylko dla HTTP, `Subject` tylko dla UI',
          en: '`BehaviorSubject` is HTTP-only, `Subject` is UI-only', ok: false },
        { pl: '`Subject` bufferuje ostatnie 10 wartości', en: '`Subject` buffers the last 10 emissions', ok: false },
        { pl: 'Nie różnią się — to aliasy', en: 'They are aliases', ok: false },
      ],
      exp: { pl: 'Alternatywnie `ReplaySubject(n)` trzyma N ostatnich; `AsyncSubject` emituje dopiero po complete.',
             en: 'Alternatives: `ReplaySubject(n)` keeps N last values, `AsyncSubject` emits only after complete.' },
      topic: { pl: 'RxJS — Subject family', en: 'RxJS — Subject family' },
    },
    {
      id: 'rx-sharereplay',
      cat: 'rxjs', type: 'single',
      q: { pl: 'Co trzeba dodać do `shareReplay(1)`, żeby uniknąć wycieku przy źródle nigdy niekończącym się (np. WebSocket)?',
           en: 'What do you add to `shareReplay(1)` to avoid leaks on a never-completing source (e.g. WebSocket)?' },
      a: [
        { pl: 'Konfigurację `{ bufferSize: 1, refCount: true }`', en: 'The `{ bufferSize: 1, refCount: true }` config', ok: true },
        { pl: 'Operator `take(1)` przed nim', en: 'A `take(1)` before it', ok: false },
        { pl: '`retry(Infinity)`', en: '`retry(Infinity)`', ok: false },
        { pl: '`distinctUntilChanged()`', en: '`distinctUntilChanged()`', ok: false },
      ],
      exp: { pl: '`refCount: true` powoduje odłączenie od source gdy wszyscy subskrybenci znikną. Bez tego source żyje wiecznie = leak.',
             en: '`refCount: true` disconnects from the source when all subscribers leave. Without it the source lives forever = leak.' },
      topic: { pl: 'shareReplay — refCount', en: 'shareReplay — refCount' },
    },
    {
      id: 'rx-hot-cold',
      cat: 'rxjs', type: 'multi',
      q: { pl: 'Które Observable są "hot" z natury?',
           en: 'Which observables are "hot" by nature?' },
      a: [
        { pl: '`fromEvent(input, "click")`', en: '`fromEvent(input, "click")`', ok: true },
        { pl: '`webSocket(...)` (broadcast wszystkim subskrybentom)', en: '`webSocket(...)` (broadcast to all subscribers)', ok: true },
        { pl: '`http.get(url)`', en: '`http.get(url)`', ok: false },
        { pl: '`Subject` po wywołaniu `.next()`', en: '`Subject` after `.next()`', ok: true },
        { pl: '`of(1, 2, 3)`', en: '`of(1, 2, 3)`', ok: false },
      ],
      exp: { pl: 'Hot = produkcja niezależna od subskrybentów (events, WS, Subjects). Cold = każdy subscribe odpala nową produkcję (HTTP, timer, of).',
             en: 'Hot = production independent of subscribers (events, WS, Subjects). Cold = each subscribe starts a new production (HTTP, timer, of).' },
      topic: { pl: 'Hot vs Cold Observables', en: 'Hot vs cold observables' },
    },

    /* ── TYPESCRIPT / JS ─────────────────────────────────── */
    {
      id: 'ts-unknown-vs-any',
      cat: 'architecture', type: 'single',
      q: { pl: 'Która różnica między `unknown` a `any` jest kluczowa?',
           en: 'What is the key difference between `unknown` and `any`?' },
      a: [
        { pl: '`unknown` wymaga zawężenia typu przed użyciem; `any` wyłącza typowanie',
          en: '`unknown` requires narrowing before use; `any` disables type checking', ok: true },
        { pl: '`unknown` jest tylko dla funkcji, `any` dla klas', en: '`unknown` is only for functions, `any` for classes', ok: false },
        { pl: '`unknown` jest aliasem `any`', en: '`unknown` is an alias of `any`', ok: false },
        { pl: '`any` nie może być przekazany do `JSON.parse`', en: '`any` cannot be passed to `JSON.parse`', ok: false },
      ],
      exp: { pl: 'Senior zawsze preferuje `unknown` dla danych zewnętrznych (JSON, localStorage, postMessage) — TS wymusi walidację przed użyciem.',
             en: 'Seniors prefer `unknown` for external data (JSON, localStorage, postMessage) — TS forces validation before usage.' },
      topic: { pl: 'TypeScript — unknown vs any', en: 'TypeScript — unknown vs any' },
    },
    {
      id: 'ts-satisfies',
      cat: 'architecture', type: 'single',
      q: { pl: 'Co daje operator `satisfies` w porównaniu do zwykłego type assertion (`as`)?',
           en: 'What does the `satisfies` operator give you over a `as` assertion?' },
      a: [
        { pl: 'Sprawdza, że wartość pasuje do typu, ale zachowuje wąski typ literalny',
          en: 'Checks the value matches the type while keeping the narrow literal type', ok: true },
        { pl: 'Szybszy runtime', en: 'Better runtime performance', ok: false },
        { pl: 'Zmienia typ na dowolny inny', en: 'Casts to any other type', ok: false },
        { pl: 'Generuje runtime check', en: 'Generates a runtime check', ok: false },
      ],
      exp: { pl: '`as` to niebezpieczny cast (może zamaskować błąd). `satisfies` waliduje bez szerokiego rzutowania — `typeof config.theme` zostaje `"dark"` zamiast `string`.',
             en: '`as` is an unsafe cast (can hide bugs). `satisfies` validates without widening — `typeof config.theme` stays `"dark"` instead of `string`.' },
      topic: { pl: 'TypeScript — satisfies', en: 'TypeScript — satisfies' },
    },
    {
      id: 'js-event-loop',
      cat: 'architecture', type: 'single',
      q: { pl: 'Jaka będzie kolejność wyjścia?<br><code>console.log(1); setTimeout(()=>console.log(2)); Promise.resolve().then(()=>console.log(3)); console.log(4);</code>',
           en: 'What is the output order?<br><code>console.log(1); setTimeout(()=>console.log(2)); Promise.resolve().then(()=>console.log(3)); console.log(4);</code>' },
      a: [
        { pl: '1, 4, 3, 2', en: '1, 4, 3, 2', ok: true },
        { pl: '1, 2, 3, 4', en: '1, 2, 3, 4', ok: false },
        { pl: '1, 4, 2, 3', en: '1, 4, 2, 3', ok: false },
        { pl: '1, 3, 4, 2', en: '1, 3, 4, 2', ok: false },
      ],
      exp: { pl: 'Najpierw synchroniczne (1, 4), potem wszystkie microtasks (3 — Promise callback), a dopiero na końcu macrotask (2 — setTimeout).',
             en: 'Sync code runs first (1, 4), then all microtasks (3 — Promise callback), then macrotasks (2 — setTimeout).' },
      topic: { pl: 'JS — event loop, microtasks', en: 'JS — event loop, microtasks' },
    },
    {
      id: 'ts-utility-types',
      cat: 'architecture', type: 'multi',
      q: { pl: 'Które z utility types poprawnie tworzą wąski pod-typ istniejącego typu?',
           en: 'Which utility types correctly create a narrower sub-type of an existing type?' },
      a: [
        { pl: '`Pick<T, K>`', en: '`Pick<T, K>`', ok: true },
        { pl: '`Omit<T, K>`', en: '`Omit<T, K>`', ok: true },
        { pl: '`ReturnType<F>`', en: '`ReturnType<F>`', ok: true },
        { pl: '`NarrowOf<T>`', en: '`NarrowOf<T>`', ok: false },
        { pl: '`ExtractKeys<T>`', en: '`ExtractKeys<T>`', ok: false },
      ],
      exp: { pl: 'Pick, Omit i ReturnType są wbudowane w TS. NarrowOf i ExtractKeys nie istnieją — to pułapka z fałszywymi nazwami.',
             en: 'Pick, Omit and ReturnType are built-in. NarrowOf and ExtractKeys do not exist — trap with fake names.' },
      topic: { pl: 'TypeScript — utility types', en: 'TypeScript — utility types' },
    },

    /* ── CSS / HTML / SCSS ───────────────────────────────── */
    {
      id: 'css-grid-vs-flex',
      cat: 'css', type: 'single',
      q: { pl: 'Kiedy Grid ma naturalną przewagę nad Flexbox?',
           en: 'When does Grid have a natural advantage over Flexbox?' },
      a: [
        { pl: 'Gdy layout jest dwuwymiarowy (rzędy i kolumny jednocześnie)',
          en: 'When the layout is two-dimensional (rows AND columns at once)', ok: true },
        { pl: 'Zawsze — Flexbox jest deprecated', en: 'Always — Flexbox is deprecated', ok: false },
        { pl: 'Przy centrowaniu pojedynczego elementu', en: 'For centering a single element', ok: false },
        { pl: 'Przy animacjach', en: 'For animations', ok: false },
      ],
      exp: { pl: 'Flex = 1D (nawigacja, jeden rząd kart). Grid = 2D (dashboard, cała strona). Często zagnieżdżane: Grid na layout, Flex wewnątrz kart.',
             en: 'Flex = 1D (nav, row of cards). Grid = 2D (dashboard, full page). Often nested: Grid for layout, Flex inside cards.' },
      topic: { pl: 'CSS — Grid vs Flex', en: 'CSS — Grid vs Flex' },
    },
    {
      id: 'css-container-queries',
      cat: 'css', type: 'single',
      q: { pl: 'Kiedy `@container` wygrywa z `@media`?',
           en: 'When does `@container` beat `@media`?' },
      a: [
        { pl: 'Gdy ten sam komponent musi wyglądać inaczej w szerokim main i wąskim sidebarze na tej samej stronie',
          en: 'When the same component must look different in a wide main and a narrow sidebar on the same page', ok: true },
        { pl: 'Gdy chcemy reagować na dark mode', en: 'When reacting to dark mode', ok: false },
        { pl: 'Dla drukarki', en: 'For print', ok: false },
        { pl: 'Dla orientacji ekranu', en: 'For screen orientation', ok: false },
      ],
      exp: { pl: 'Media queries patrzą tylko na viewport. Container queries na rozmiar rodzica — komponent sam reaguje niezależnie od tego, gdzie został wrzucony.',
             en: 'Media queries look at the viewport only. Container queries look at the parent size — the component adapts regardless of where it is placed.' },
      topic: { pl: 'CSS — Container Queries', en: 'CSS — Container Queries' },
    },
    {
      id: 'css-has',
      cat: 'css', type: 'single',
      q: { pl: 'Co robi selektor `:has()` w CSS?',
           en: 'What does the `:has()` selector do?' },
      a: [
        { pl: 'Pozwala stylować rodzica na podstawie istnienia określonego dziecka',
          en: 'Lets you style a parent based on the presence of a specific descendant', ok: true },
        { pl: 'Sprawdza, czy element ma klasę', en: 'Checks if an element has a class', ok: false },
        { pl: 'Usuwa element z DOM', en: 'Removes an element from the DOM', ok: false },
        { pl: 'Oznacza hover', en: 'Marks hover', ok: false },
      ],
      exp: { pl: '`form:has(:invalid) button { opacity: .5 }` — typowe użycie: stylowanie kontenera na podstawie stanu dzieci bez JS.',
             en: '`form:has(:invalid) button { opacity: .5 }` — typical use: style a container based on child state without JS.' },
      topic: { pl: 'CSS — selektor :has()', en: 'CSS — :has() selector' },
    },
    {
      id: 'scss-use-vs-import',
      cat: 'css', type: 'single',
      q: { pl: 'Dlaczego `@use` jest preferowane nad `@import` w Sass?',
           en: 'Why is `@use` preferred over `@import` in Sass?' },
      a: [
        { pl: 'Ma namespace, nie duplikuje kodu i jest oficjalnym następcą — `@import` jest deprecated',
          en: 'It namespaces, does not duplicate output, and is the official successor — `@import` is deprecated', ok: true },
        { pl: 'Jest szybsze w runtime przeglądarki', en: 'It is faster at runtime in the browser', ok: false },
        { pl: 'Obsługuje CSS custom properties, `@import` nie', en: 'It supports CSS custom properties, `@import` does not', ok: false },
        { pl: 'Jest jedynym sposobem ładowania plików `.css`', en: 'It is the only way to load `.css` files', ok: false },
      ],
      exp: { pl: '`@use "tokens" as t;` → `t.$accent`. Bez globalnego leaku, bez duplikacji przy wielokrotnym użyciu.',
             en: '`@use "tokens" as t;` → `t.$accent`. No global leaks, no duplication across imports.' },
      topic: { pl: 'SCSS — @use vs @import', en: 'SCSS — @use vs @import' },
    },

    /* ── REST / HTTP / WS ────────────────────────────────── */
    {
      id: 'http-jwt-storage',
      cat: 'architecture', type: 'single',
      q: { pl: 'Gdzie najlepiej trzymać tokeny w SPA dla bezpieczeństwa?',
           en: 'Where should you store tokens in a SPA for best security?' },
      a: [
        { pl: 'refresh_token w httpOnly Secure cookie, access_token w pamięci (signal/serwis)',
          en: 'refresh_token in an httpOnly Secure cookie, access_token in memory (signal/service)', ok: true },
        { pl: 'Oba w localStorage — najprostsze', en: 'Both in localStorage — simplest', ok: false },
        { pl: 'Oba w sessionStorage', en: 'Both in sessionStorage', ok: false },
        { pl: 'W adresie URL jako query params', en: 'In the URL as query params', ok: false },
      ],
      exp: { pl: 'localStorage jest dostępny dla XSS. httpOnly cookie chroni refresh_token przed JS. Access_token w pamięci ginie przy reload — to akceptowalne, bo i tak krótko żyje.',
             en: 'localStorage is readable by XSS. httpOnly cookies protect the refresh_token from JS. Access_token in memory is lost on reload — acceptable since it is short-lived anyway.' },
      topic: { pl: 'HTTP Auth — storage tokenów', en: 'HTTP auth — token storage' },
    },
    {
      id: 'http-ws-vs-sse',
      cat: 'architecture', type: 'single',
      q: { pl: 'Dla prostych powiadomień serwer→klient lepsze jest:',
           en: 'For simple server→client notifications, better choice is:' },
      a: [
        { pl: 'Server-Sent Events (SSE) — prostsze, auto-reconnect, HTTP-based',
          en: 'Server-Sent Events (SSE) — simpler, auto-reconnect, HTTP-based', ok: true },
        { pl: 'Zawsze WebSocket, bo nowocześniejsze', en: 'Always WebSocket because it is more modern', ok: false },
        { pl: 'Polling co 500 ms', en: 'Polling every 500 ms', ok: false },
        { pl: 'gRPC-Web Bidi', en: 'gRPC-Web bidi', ok: false },
      ],
      exp: { pl: 'WS = dwukierunkowe (chat, collab). SSE = jednokierunkowe server → client (notyfikacje, live feed) — prostsze w implementacji i debugu.',
             en: 'WS = bi-directional (chat, collab). SSE = one-way server → client (notifications, live feed) — simpler to implement and debug.' },
      topic: { pl: 'WebSockets vs SSE', en: 'WebSockets vs SSE' },
    },
    {
      id: 'http-cors-preflight',
      cat: 'architecture', type: 'single',
      q: { pl: 'Co wyzwala preflight OPTIONS w CORS?',
           en: 'What triggers a CORS preflight OPTIONS?' },
      a: [
        { pl: 'Custom header (np. `Authorization`, `X-Api-Key`) albo metoda inna niż GET/POST/HEAD',
          en: 'A custom header (e.g. `Authorization`, `X-Api-Key`) or a method other than GET/POST/HEAD', ok: true },
        { pl: 'Każdy request cross-origin', en: 'Any cross-origin request', ok: false },
        { pl: 'Tylko POST z `Content-Type: application/x-www-form-urlencoded`', en: 'Only POST with `Content-Type: application/x-www-form-urlencoded`', ok: false },
        { pl: 'Preflight robi przeglądarka tylko w dev mode', en: 'The browser only does preflight in dev mode', ok: false },
      ],
      exp: { pl: 'Simple request (GET/POST/HEAD z bezpiecznymi nagłówkami i Content-Type: text/plain | multipart/form-data | application/x-www-form-urlencoded) nie wymaga preflight.',
             en: 'A simple request (GET/POST/HEAD with safe headers and Content-Type: text/plain | multipart/form-data | application/x-www-form-urlencoded) skips preflight.' },
      topic: { pl: 'CORS — preflight', en: 'CORS — preflight' },
    },

    /* ── FORMS ───────────────────────────────────────────── */
    {
      id: 'form-reactive-vs-template',
      cat: 'forms', type: 'single',
      q: { pl: 'Co rekomendujesz dla dużego, typowanego formularza enterprise?',
           en: 'What do you recommend for a large, typed enterprise form?' },
      a: [
        { pl: 'Reactive Forms z `NonNullableFormBuilder` i silnym typowaniem',
          en: 'Reactive Forms with `NonNullableFormBuilder` and strong typing', ok: true },
        { pl: 'Template-driven z `ngModel`, bo mniej kodu', en: 'Template-driven with `ngModel` — less code', ok: false },
        { pl: 'Ręczne inputy + walidacja w `ngSubmit`', en: 'Plain inputs + validation in `ngSubmit`', ok: false },
        { pl: 'Tylko Signal Forms — Reactive jest deprecated', en: 'Only Signal Forms — Reactive is deprecated', ok: false },
      ],
      exp: { pl: 'Reactive daje typowanie, testowalność, kompozycję i pełną kontrolę. Signal Forms to komplementarne API, nie zamiennik — Reactive nie jest deprecated.',
             en: 'Reactive offers typing, testability, composition and full control. Signal Forms is a complementary API, not a replacement — Reactive is not deprecated.' },
      topic: { pl: 'Formularze — Reactive vs Template-driven', en: 'Forms — Reactive vs Template-driven' },
    },
    {
      id: 'form-async-validator',
      cat: 'forms', type: 'multi',
      q: { pl: 'Które elementy są niezbędne dla poprawnego async walidatora (unikalność username)?',
           en: 'Which elements are essential for a correct async validator (unique username)?' },
      a: [
        { pl: '`debounceTime` aby nie uderzać API przy każdym wciśnięciu klawisza',
          en: '`debounceTime` so the API is not hit on every keystroke', ok: true },
        { pl: '`switchMap` dla anulowania poprzedniego requestu',
          en: '`switchMap` to cancel the previous request', ok: true },
        { pl: '`distinctUntilChanged` — pomija duplikaty tej samej wartości',
          en: '`distinctUntilChanged` to skip duplicate values', ok: true },
        { pl: '`catchError` zwracający `of(null)` — nieudany request nie powinien blokować formularza',
          en: '`catchError` returning `of(null)` — failed requests should not block the form', ok: true },
        { pl: '`shareReplay(Infinity)`', en: '`shareReplay(Infinity)`', ok: false },
      ],
      exp: { pl: 'To klasyczny wzorzec: debounce → distinct → switchMap → catchError(of(null)). `shareReplay(Infinity)` utrzymałby stare odpowiedzi i popsułby walidację.',
             en: 'Classic pattern: debounce → distinct → switchMap → catchError(of(null)). `shareReplay(Infinity)` would cache stale answers and break validation.' },
      topic: { pl: 'Formularze — walidator async', en: 'Forms — async validator' },
    },

    /* ── PERFORMANCE ─────────────────────────────────────── */
    {
      id: 'perf-web-vitals',
      cat: 'performance', type: 'multi',
      q: { pl: 'Które Web Vital ma rekomendowany próg ≤ 2.5 s?',
           en: 'Which Web Vital has a recommended threshold of ≤ 2.5s?' },
      a: [
        { pl: 'LCP (Largest Contentful Paint)', en: 'LCP (Largest Contentful Paint)', ok: true },
        { pl: 'CLS', en: 'CLS', ok: false },
        { pl: 'INP', en: 'INP', ok: false },
        { pl: 'TBT', en: 'TBT', ok: false },
      ],
      exp: { pl: 'LCP ≤ 2.5 s. CLS ≤ 0.1. INP ≤ 200 ms. TBT ≤ 200 ms. Dobre wartości core web vitals = lepsze SEO.',
             en: 'LCP ≤ 2.5s. CLS ≤ 0.1. INP ≤ 200ms. TBT ≤ 200ms. Good core web vitals = better SEO.' },
      topic: { pl: 'Core Web Vitals', en: 'Core Web Vitals' },
    },
    {
      id: 'perf-ngoptimizedimage',
      cat: 'performance', type: 'single',
      q: { pl: 'Co daje `NgOptimizedImage`?',
           en: 'What does `NgOptimizedImage` give you?' },
      a: [
        { pl: 'Lazy loading, priorytety dla LCP, automatyczny srcset i ostrzeżenia w dev mode',
          en: 'Lazy loading, LCP priority hints, auto srcset and dev-mode warnings', ok: true },
        { pl: 'Automatyczny WebP conversion w przeglądarce', en: 'Automatic WebP conversion in the browser', ok: false },
        { pl: 'Upload do CDN', en: 'CDN upload', ok: false },
        { pl: 'Dynamiczne crop na GPU', en: 'GPU dynamic cropping', ok: false },
      ],
      exp: { pl: 'Dyrektywa `ngSrc` + `priority`, `width`, `height`, `sizes`. W dev warn-uje o missing dimensions, dużych nieoptymalizowanych obrazkach.',
             en: 'The `ngSrc` directive + `priority`, `width`, `height`, `sizes`. In dev it warns about missing dimensions and unoptimized large images.' },
      topic: { pl: 'Performance — NgOptimizedImage', en: 'Performance — NgOptimizedImage' },
    },
    {
      id: 'perf-long-list',
      cat: 'performance', type: 'multi',
      q: { pl: 'Lista 10 000 elementów zacina scroll. Które rozwiązania pomogą?',
           en: 'A 10 000-item list janks on scroll. Which solutions help?' },
      a: [
        { pl: 'Virtual scrolling (`<cdk-virtual-scroll-viewport>`)', en: 'Virtual scrolling (`<cdk-virtual-scroll-viewport>`)', ok: true },
        { pl: 'Zamiana komponentu dziecka na `OnPush`', en: 'Switch the child component to `OnPush`', ok: true },
        { pl: 'Użycie `track item.id` w `@for`', en: 'Use `track item.id` in `@for`', ok: true },
        { pl: 'Pętla `setTimeout(..., 0)` dla każdego itemu', en: 'A `setTimeout(..., 0)` loop per item', ok: false },
        { pl: '`console.log` przy każdym renderze', en: '`console.log` on each render', ok: false },
      ],
      exp: { pl: 'Virtual scrolling renderuje tylko widoczny fragment. OnPush + track zmniejsza pracę CD. setTimeout i log tylko pogarszają problem.',
             en: 'Virtual scrolling only renders the visible portion. OnPush + track reduces CD work. setTimeout and logs only make it worse.' },
      topic: { pl: 'Wydajność długich list', en: 'Performance — long lists' },
    },

    /* ── TESTING ─────────────────────────────────────────── */
    {
      id: 'test-pyramid',
      cat: 'testing', type: 'single',
      q: { pl: 'Jaki jest zdrowy podział testów w piramidzie testów?',
           en: 'What is a healthy split in the testing pyramid?' },
      a: [
        { pl: '~70% unit, ~20% integration, ~10% e2e', en: '~70% unit, ~20% integration, ~10% e2e', ok: true },
        { pl: '~10% unit, ~20% integration, ~70% e2e', en: '~10% unit, ~20% integration, ~70% e2e', ok: false },
        { pl: '100% e2e — tylko to się liczy', en: '100% e2e — only that matters', ok: false },
        { pl: '50% unit, 50% snapshot', en: '50% unit, 50% snapshot', ok: false },
      ],
      exp: { pl: 'Odwrócona piramida (dużo e2e) daje wolne, flaky testy i niskie zaufanie. Unit są szybkie, izolowane i łatwe w utrzymaniu.',
             en: 'The inverted pyramid (lots of e2e) gives slow, flaky tests and low confidence. Units are fast, isolated, easy to maintain.' },
      topic: { pl: 'Piramida testów', en: 'Testing pyramid' },
    },
    {
      id: 'test-jest-vs-vitest',
      cat: 'testing', type: 'multi',
      q: { pl: 'Dlaczego w 2026 Vitest jest rekomendowany dla nowego projektu Angular?',
           en: 'Why is Vitest recommended for a new Angular project in 2026?' },
      a: [
        { pl: 'Natywny ESM — brak konfiguracji `@swc/jest` i transformów',
          en: 'Native ESM — no `@swc/jest` or transform config needed', ok: true },
        { pl: 'Znacząco szybszy start i watch mode',
          en: 'Much faster startup and watch mode', ok: true },
        { pl: 'Kompatybilne API z Jest — migracja niemal bez zmian',
          en: 'Jest-compatible API — migration is almost drop-in', ok: true },
        { pl: 'Official support w Angular (od v19)',
          en: 'Official Angular support (since v19)', ok: true },
        { pl: 'Jest jest oficjalnie usunięty z npm', en: 'Jest was officially removed from npm', ok: false },
      ],
      exp: { pl: 'Vitest stoi na Vite + esbuild. Angular ma oficjalny builder dla Vitest. Jest dalej działa, ale ESM w monorepo Angular/Nx nie zawsze gra gładko.',
             en: 'Vitest runs on Vite + esbuild. Angular ships an official Vitest builder. Jest still works, but ESM in an Angular/Nx monorepo can be rough.' },
      topic: { pl: 'Jest vs Vitest 2026', en: 'Jest vs Vitest 2026' },
    },
    {
      id: 'test-httpmock',
      cat: 'testing', type: 'single',
      q: { pl: 'Do mockowania HttpClient w testach Angular używasz:',
           en: 'To mock HttpClient in Angular tests you use:' },
      a: [
        { pl: '`provideHttpClientTesting()` + `HttpTestingController`',
          en: '`provideHttpClientTesting()` + `HttpTestingController`', ok: true },
        { pl: '`jest.mock("@angular/common/http")`', en: '`jest.mock("@angular/common/http")`', ok: false },
        { pl: 'Ręcznie podmieniasz `fetch` globalnie', en: 'Manually patching global `fetch`', ok: false },
        { pl: 'Nie mockujesz — uderzasz do realnego API', en: 'You do not mock — hit the real API', ok: false },
      ],
      exp: { pl: '`HttpTestingController.expectOne(url).flush(response)` — pełna kontrola nad odpowiedziami, weryfikacja, brak nadmiarowych calls.',
             en: '`HttpTestingController.expectOne(url).flush(response)` — full control over responses, verification, no extra calls.' },
      topic: { pl: 'Angular — testowanie HttpClient', en: 'Angular — HttpClient testing' },
    },

    /* ── ARCHITECTURE / PATTERNS ─────────────────────────── */
    {
      id: 'arch-solid-o',
      cat: 'architecture', type: 'single',
      q: { pl: 'Co oznacza literka "O" w SOLID?',
           en: 'What does the "O" in SOLID stand for?' },
      a: [
        { pl: 'Open/Closed — otwarte na rozszerzenie, zamknięte na modyfikację',
          en: 'Open/Closed — open for extension, closed for modification', ok: true },
        { pl: 'Observer — wzorzec projektowy', en: 'Observer — a design pattern', ok: false },
        { pl: 'Optimization — optymalizacja', en: 'Optimization', ok: false },
        { pl: 'Orthogonality', en: 'Orthogonality', ok: false },
      ],
      exp: { pl: 'Open/Closed — dodaj nowy provider / strategy zamiast edytować istniejące. W Angularze świetnie realizowane przez DI i tokeny interfejsowe.',
             en: 'Open/Closed — add a new provider/strategy instead of editing existing code. Angular realizes this beautifully via DI and interface tokens.' },
      topic: { pl: 'SOLID — Open/Closed', en: 'SOLID — Open/Closed' },
    },
    {
      id: 'arch-smart-dumb',
      cat: 'architecture', type: 'single',
      q: { pl: 'Komponent "presentational" (dumb) powinien:',
           en: 'A "presentational" (dumb) component should:' },
      a: [
        { pl: 'Przyjmować dane przez `input()` i emitować zdarzenia przez `output()` bez dostępu do serwisów biznesowych',
          en: 'Take data via `input()` and emit events via `output()`, without injecting business services', ok: true },
        { pl: 'Wstrzykiwać store i fetchować dane', en: 'Inject a store and fetch data itself', ok: false },
        { pl: 'Zawierać logikę routingu', en: 'Contain routing logic', ok: false },
        { pl: 'Być zawsze lazy loadowany', en: 'Always be lazy-loaded', ok: false },
      ],
      exp: { pl: 'Presentational = pure UI (łatwo testowalny, reużywalny, łatwo stylowalny). Smart container trzyma stan, wstrzykuje serwisy i przekazuje dane do dumb.',
             en: 'Presentational = pure UI (easy to test, reuse, style). The smart container owns state, injects services, and feeds data to dumb components.' },
      topic: { pl: 'Smart / Presentational', en: 'Smart / Presentational' },
    },
    {
      id: 'arch-facade',
      cat: 'architecture', type: 'single',
      q: { pl: 'Wzorzec Facade w Angular najczęściej używa się do:',
           en: 'The Facade pattern in Angular is most often used to:' },
      a: [
        { pl: 'Ukrycia skomplikowanego state managementu (np. NgRx selectors + dispatch) za prostym API serwisu',
          en: 'Hide complex state management (e.g. NgRx selectors + dispatch) behind a simple service API', ok: true },
        { pl: 'Generowania klas na podstawie OpenAPI', en: 'Generating classes from OpenAPI', ok: false },
        { pl: 'Jako alternatywa dla `HttpClient`', en: 'As an alternative to `HttpClient`', ok: false },
        { pl: 'Automatycznego cache\'owania GET-ów', en: 'Automatic GET caching', ok: false },
      ],
      exp: { pl: 'Np. `CheckoutFacade` z metodami `addItem`, `removeItem`, `total$` — UI nie wie, czy pod spodem NgRx, Signal Store czy Subject.',
             en: 'E.g. `CheckoutFacade` with `addItem`, `removeItem`, `total$` — the UI does not know whether NgRx, Signal Store or a Subject is behind it.' },
      topic: { pl: 'Pattern — Facade', en: 'Pattern — Facade' },
    },

    /* ── MICROFRONTENDS ──────────────────────────────────── */
    {
      id: 'mf-when',
      cat: 'architecture', type: 'single',
      q: { pl: 'Kiedy mikrofrontendy są realnie uzasadnione?',
           en: 'When are microfrontends actually justified?' },
      a: [
        { pl: 'Przy 5+ niezależnych zespołach i wymogu niezależnego deployu',
          en: 'With 5+ independent teams and a requirement for independent deploys', ok: true },
        { pl: 'Zawsze, gdy projekt > 10k linii kodu', en: 'Always when the project exceeds 10k lines', ok: false },
        { pl: 'W każdej SPA od początku', en: 'In every SPA from day one', ok: false },
        { pl: 'Tylko w Reactcie', en: 'Only in React projects', ok: false },
      ],
      exp: { pl: 'MF to koszt (infra, routing, shared deps, auth). Dla <5 zespołów monorepo (Nx) wygrywa pod każdym kątem.',
             en: 'MF has a cost (infra, routing, shared deps, auth). For <5 teams a monorepo (Nx) wins on every axis.' },
      topic: { pl: 'Mikrofrontendy — kiedy używać', en: 'Microfrontends — when to use' },
    },
    {
      id: 'mf-shared-deps',
      cat: 'architecture', type: 'single',
      q: { pl: 'Największa pułapka przy Module Federation w Angular:',
           en: 'Biggest trap with Module Federation in Angular:' },
      a: [
        { pl: 'Zduplikowane instancje Angulara w różnych remote-ach — `inject()` zwraca różne instancje serwisów',
          en: 'Duplicated Angular instances across remotes — `inject()` returns different service instances', ok: true },
        { pl: 'Module Federation nie działa ze standalone components', en: 'Module Federation does not work with standalone components', ok: false },
        { pl: 'Wymaga CommonJS', en: 'It requires CommonJS', ok: false },
        { pl: 'Działa tylko w Chromium', en: 'It only works in Chromium', ok: false },
      ],
      exp: { pl: 'Rozwiązanie: dokładnie skonfigurowane `shared` z `singleton: true` i zgodnymi wersjami między host a remote-ami.',
             en: 'Fix: precise `shared` config with `singleton: true` and matching versions across host and remotes.' },
      topic: { pl: 'Module Federation — shared deps', en: 'Module Federation — shared deps' },
    },

    /* ── GIT / NODE / NPM ────────────────────────────────── */
    {
      id: 'git-rebase-merge',
      cat: 'devops', type: 'single',
      q: { pl: 'Rekomendowany flow mergowania PR-ów w zespole z code review:',
           en: 'Recommended PR merge flow in a team with code review:' },
      a: [
        { pl: 'Squash merge do main + lokalny rebase do aktualizacji feature brancha',
          en: 'Squash merge into main + local rebase to keep the feature branch updated', ok: true },
        { pl: 'Zawsze `git merge --no-ff`', en: 'Always `git merge --no-ff`', ok: false },
        { pl: 'Force push do main po każdym commit', en: 'Force push to main after every commit', ok: false },
        { pl: 'Push bezpośrednio do main bez PR', en: 'Push directly to main without a PR', ok: false },
      ],
      exp: { pl: 'Squash daje czystą historię main (1 commit = 1 feature). Rebase lokalny utrzymuje feature branch aktualny bez merge commits.',
             en: 'Squash yields a clean main history (1 commit = 1 feature). Local rebase keeps the feature branch fresh without merge commits.' },
      topic: { pl: 'Git — squash vs merge vs rebase', en: 'Git — squash vs merge vs rebase' },
    },
    {
      id: 'pnpm-advantage',
      cat: 'devops', type: 'multi',
      q: { pl: 'Dlaczego pnpm wygrywa w 2026 nad npm/yarn?',
           en: 'Why does pnpm win over npm/yarn in 2026?' },
      a: [
        { pl: 'Hardlinks do globalnego store — oszczędność miejsca',
          en: 'Hardlinks to a global store — disk space savings', ok: true },
        { pl: 'Strict resolution — brak phantom dependencies', en: 'Strict resolution — no phantom dependencies', ok: true },
        { pl: 'Szybsza instalacja, szczególnie w monorepo', en: 'Faster install, especially in monorepos', ok: true },
        { pl: 'Jest jedynym menedżerem wspierającym workspaces', en: 'It is the only manager supporting workspaces', ok: false },
      ],
      exp: { pl: 'Workspaces wspierają też npm i yarn. Główna przewaga pnpm: miejsce, szybkość, strict resolution (phantom deps = zależność używana ale nie zadeklarowana).',
             en: 'Workspaces are supported in npm and yarn too. pnpm wins on disk usage, speed, and strict resolution (phantom deps = a dep used but not declared).' },
      topic: { pl: 'npm vs pnpm vs yarn', en: 'npm vs pnpm vs yarn' },
    },

    /* ── AGILE ───────────────────────────────────────────── */
    {
      id: 'agile-scrum-vs-kanban',
      cat: 'devops', type: 'single',
      q: { pl: 'Kanban zamiast Scrum jest dobrym wyborem, gdy:',
           en: 'Kanban is a better choice than Scrum when:' },
      a: [
        { pl: 'Praca ma wysoki przepływ zadań o różnym priorytecie — np. ops/support',
          en: 'Work has a high throughput of varied-priority tasks — e.g. ops/support', ok: true },
        { pl: 'Zespół jest mały (1-2 osoby)', en: 'The team is tiny (1-2 people)', ok: false },
        { pl: 'Budżet jest napięty', en: 'The budget is tight', ok: false },
        { pl: 'PO nie istnieje', en: 'There is no PO', ok: false },
      ],
      exp: { pl: 'Scrum = złożony produkt z rytmem sprintów. Kanban = continuous flow, WIP limits. Typowo: dev team = Scrum, support = Kanban.',
             en: 'Scrum = complex product with a sprint rhythm. Kanban = continuous flow + WIP limits. Typically: dev team = Scrum, support = Kanban.' },
      topic: { pl: 'Agile — Scrum vs Kanban', en: 'Agile — Scrum vs Kanban' },
    },

    /* ── PWA / MODERN WEB ────────────────────────────────── */
    {
      id: 'pwa-service-worker',
      cat: 'pwa', type: 'single',
      q: { pl: 'Głównym zadaniem Service Workera w PWA jest:',
           en: 'The main role of a Service Worker in a PWA is:' },
      a: [
        { pl: 'Pośredniczenie między aplikacją a siecią: cache, offline, push notifications',
          en: 'Proxying between the app and the network: cache, offline, push notifications', ok: true },
        { pl: 'Zastąpienie głównego wątku JS', en: 'Replacing the main JS thread', ok: false },
        { pl: 'Uruchamianie kodu bez HTTPS', en: 'Running code without HTTPS', ok: false },
        { pl: 'Budowanie aplikacji', en: 'Building the application', ok: false },
      ],
      exp: { pl: 'SW działa jak proxy sieciowy — strategie cache (cache-first, stale-while-revalidate), offline fallback, background sync, push.',
             en: 'SW acts as a network proxy — caching strategies (cache-first, stale-while-revalidate), offline fallback, background sync, push.' },
      topic: { pl: 'PWA — Service Worker', en: 'PWA — Service Worker' },
    },

    /* ── CAMUNDA / BPM ───────────────────────────────────── */
    {
      id: 'cam-7-vs-8',
      cat: 'camunda', type: 'multi',
      q: { pl: 'Które stwierdzenia o Camunda 7 vs 8 są prawdziwe?',
           en: 'Which statements about Camunda 7 vs 8 are correct?' },
      a: [
        { pl: 'Camunda 7 używa relacyjnej bazy, Camunda 8 (Zeebe) używa event-sourced engine',
          en: 'Camunda 7 uses a relational DB, Camunda 8 (Zeebe) uses an event-sourced engine', ok: true },
        { pl: 'Camunda 8 lepiej skaluje się poziomo (cloud-native)',
          en: 'Camunda 8 scales out horizontally better (cloud-native)', ok: true },
        { pl: 'REST API Tasklist jest identyczne w obu wersjach',
          en: 'The Tasklist REST API is identical in both versions', ok: false },
        { pl: 'Camunda 8 preferuje gRPC (Zeebe) plus osobne REST API Tasklist/Operate',
          en: 'Camunda 8 prefers gRPC (Zeebe) plus separate Tasklist/Operate REST APIs', ok: true },
      ],
      exp: { pl: 'Integracja frontu: w C7 łączysz się z jednym REST API. W C8 Tasklist/Operate mają osobne REST, a engine rozmawia przez gRPC. Przy migracji z C7→C8 trzeba zmienić kontrakty API.',
             en: 'Frontend integration: in C7 you hit one REST API. In C8 Tasklist/Operate have separate REST APIs and the engine talks gRPC. Migrating C7→C8 means changing API contracts.' },
      topic: { pl: 'Camunda 7 vs Camunda 8', en: 'Camunda 7 vs Camunda 8' },
    },
    {
      id: 'cam-tasklist-flow',
      cat: 'camunda', type: 'single',
      q: { pl: 'Jaka jest poprawna sekwencja do obsługi user-taska w Camunda Tasklist przez operatora?',
           en: 'What is the correct sequence to handle a user task in Camunda Tasklist by an operator?' },
      a: [
        { pl: 'list → claim → (fetch form / variables) → submit-form (complete)',
          en: 'list → claim → (fetch form / variables) → submit-form (complete)', ok: true },
        { pl: 'complete → list → claim', en: 'complete → list → claim', ok: false },
        { pl: 'claim → list → submit', en: 'claim → list → submit', ok: false },
        { pl: 'list → submit-form → claim', en: 'list → submit-form → claim', ok: false },
      ],
      exp: { pl: 'Najpierw wyszukujesz taski (`GET /task?assignee=...`), claim przypisuje ciebie (blokuje dla innych), potem dociągasz formularz/variables, a `submit-form` kończy task i przesyła zmienne procesu.',
             en: 'First list tasks (`GET /task?assignee=...`), claim assigns you (locks out others), then fetch form/variables, and `submit-form` completes the task and submits process variables.' },
      topic: { pl: 'Camunda Tasklist REST flow', en: 'Camunda Tasklist REST flow' },
    },
    {
      id: 'cam-variables-format',
      cat: 'camunda', type: 'single',
      q: { pl: 'Jak wygląda poprawny format zmiennej procesu w Camunda REST API przy submit-form?',
           en: 'What is the correct process-variable format in Camunda REST API on submit-form?' },
      a: [
        { pl: '`{ decision: { value: "approve", type: "String" } }`',
          en: '`{ decision: { value: "approve", type: "String" } }`', ok: true },
        { pl: '`{ decision: "approve" }`', en: '`{ decision: "approve" }`', ok: false },
        { pl: '`{ decision: ["approve", "String"] }`', en: '`{ decision: ["approve", "String"] }`', ok: false },
        { pl: '`{ variables: { decision: "approve" } }`', en: '`{ variables: { decision: "approve" } }`', ok: false },
      ],
      exp: { pl: 'Camunda REST wymaga obiektu `{ value, type }` dla każdej zmiennej. Typy: String, Boolean, Long, Double, Date, Json, Object. Bez `type` silnik odrzuci zmienną.',
             en: 'Camunda REST requires `{ value, type }` per variable. Types: String, Boolean, Long, Double, Date, Json, Object. Without `type` the engine rejects it.' },
      topic: { pl: 'Camunda — format zmiennych procesu', en: 'Camunda — process variable format' },
    },

    /* ── DOMENA BANKOWA: KYC / AML ───────────────────────── */
    {
      id: 'dom-kyc-layers',
      cat: 'domain', type: 'multi',
      q: { pl: 'Które stwierdzenia o KYC / CDD / EDD są prawdziwe?',
           en: 'Which statements about KYC / CDD / EDD are correct?' },
      a: [
        { pl: 'EDD (Enhanced Due Diligence) stosuje się dla klientów wysokiego ryzyka (PEP, kraje wysokiego ryzyka)',
          en: 'EDD (Enhanced Due Diligence) applies to high-risk customers (PEP, high-risk countries)', ok: true },
        { pl: 'SDD (Simplified Due Diligence) pozwala zredukować zakres weryfikacji dla klientów niskiego ryzyka',
          en: 'SDD (Simplified Due Diligence) allows reduced verification for low-risk customers', ok: true },
        { pl: 'KYC wykonuje się tylko raz przy otwarciu konta',
          en: 'KYC is performed only once, at account opening', ok: false },
        { pl: 'Monitoring transakcji i okresowy review są częścią bieżącego KYC',
          en: 'Transaction monitoring and periodic review are part of ongoing KYC', ok: true },
      ],
      exp: { pl: 'KYC to proces ciągły: onboarding → trigger-based review → periodic review (1/3/5 lat zależnie od ryzyka). EDD dla PEP, high-risk jurisdictions, skomplikowanej struktury własnościowej.',
             en: 'KYC is ongoing: onboarding → trigger-based review → periodic review (1/3/5 years by risk). EDD for PEPs, high-risk jurisdictions, complex ownership.' },
      topic: { pl: 'KYC layers — CDD / EDD / SDD', en: 'KYC layers — CDD / EDD / SDD' },
    },
    {
      id: 'dom-aml-str',
      cat: 'domain', type: 'single',
      q: { pl: 'Czym jest STR (Suspicious Transaction Report) w kontekście polskiego AML?',
           en: 'What is an STR (Suspicious Transaction Report) in Polish AML context?' },
      a: [
        { pl: 'Zgłoszenie podejrzanej transakcji do GIIF (Generalnego Inspektora Informacji Finansowej)',
          en: 'A report of a suspicious transaction to GIIF (General Inspector of Financial Information)', ok: true },
        { pl: 'Wewnętrzny raport compliance, nie idzie poza bank',
          en: 'An internal compliance report that never leaves the bank', ok: false },
        { pl: 'Raport KNF o standardach regulacyjnych', en: 'A KNF report on regulatory standards', ok: false },
        { pl: 'Kwartalny raport FATCA', en: 'A quarterly FATCA report', ok: false },
      ],
      exp: { pl: 'STR/SAR leci do GIIF (jednostki FIU). W UI operator AML musi mieć przycisk „Report to GIIF" z pełnym audit trail (who, when, why, evidence).',
             en: 'STR/SAR goes to GIIF (the FIU). AML operator UI must have a "Report to GIIF" action with a full audit trail (who, when, why, evidence).' },
      topic: { pl: 'AML — STR i GIIF', en: 'AML — STR and GIIF' },
    },

    /* ── GITHUB COPILOT / AI TOOLS ───────────────────────── */
    {
      id: 'ai-copilot-modes',
      cat: 'ai-tools', type: 'multi',
      q: { pl: 'Jakie tryby pracy oferuje GitHub Copilot w 2026?',
           en: 'What working modes does GitHub Copilot offer in 2026?' },
      a: [
        { pl: 'Inline completion (podczas pisania)', en: 'Inline completion (while typing)', ok: true },
        { pl: 'Chat (konwersacja w edytorze)', en: 'Chat (conversation in editor)', ok: true },
        { pl: 'Agent mode (autonomiczne wykonanie task-listy)',
          en: 'Agent mode (autonomous task-list execution)', ok: true },
        { pl: 'Offline on-device bez połączenia z serwerem',
          en: 'Fully offline on-device without server connection', ok: false },
      ],
      exp: { pl: 'Copilot = inline, Chat, Agent. Nie działa offline — wymaga połączenia z backendem. W banku: uwaga na Content Exclusions + Business/Enterprise tier (enterprise nie trenuje na twoim kodzie).',
             en: 'Copilot = inline, Chat, Agent. It does not work offline — needs backend. In banking: mind Content Exclusions + Business/Enterprise tier (enterprise does not train on your code).' },
      topic: { pl: 'GitHub Copilot — tryby pracy', en: 'GitHub Copilot — working modes' },
    },
    {
      id: 'ai-copilot-regulated',
      cat: 'ai-tools', type: 'single',
      q: { pl: 'Co jest najważniejsze przy używaniu Copilot w regulowanej branży (bank, KYC/AML)?',
           en: 'What is the most important thing when using Copilot in a regulated industry (bank, KYC/AML)?' },
      a: [
        { pl: 'Content Exclusions dla wrażliwych repo + review-first mindset + Enterprise/Business tier (no training)',
          en: 'Content Exclusions on sensitive repos + review-first mindset + Enterprise/Business tier (no training)', ok: true },
        { pl: 'Wyłączyć Copilot całkowicie', en: 'Disable Copilot entirely', ok: false },
        { pl: 'Ślepo ufać sugestiom — Copilot przeszedł audyt zgodności',
          en: 'Blindly trust suggestions — Copilot passed a compliance audit', ok: false },
        { pl: 'Kopiować sugestie do prod bez review, jeśli testy przechodzą',
          en: 'Copy suggestions to prod without review if tests pass', ok: false },
      ],
      exp: { pl: 'Nie ma audit-proof AI. W regulowanej branży: 1) exclude sekrety/PII/KYC-schema z indeksacji, 2) każdą sugestię traktuj jak PR od juniora — reviewuj, 3) zawsze Enterprise/Business (no training, admin audit log).',
             en: 'There is no audit-proof AI. In regulated industry: 1) exclude secrets/PII/KYC-schema from indexing, 2) treat each suggestion like a junior\'s PR — review it, 3) always Enterprise/Business (no training, admin audit log).' },
      topic: { pl: 'Copilot w regulated industry', en: 'Copilot in regulated industry' },
    },
  ];

  window.QUIZ_DATA = QUIZ_DATA;
})();
